//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdditionalFile) DeepCopyInto(out *AdditionalFile) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdditionalFile.
func (in *AdditionalFile) DeepCopy() *AdditionalFile {
	if in == nil {
		return nil
	}
	out := new(AdditionalFile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentImageSpec) DeepCopyInto(out *AgentImageSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentImageSpec.
func (in *AgentImageSpec) DeepCopy() *AgentImageSpec {
	if in == nil {
		return nil
	}
	out := new(AgentImageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentSpec) DeepCopyInto(out *AgentSpec) {
	*out = *in
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(AgentImageSpec)
		**out = **in
	}
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentSpec.
func (in *AgentSpec) DeepCopy() *AgentSpec {
	if in == nil {
		return nil
	}
	out := new(AgentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoRollbackSpec) DeepCopyInto(out *AutoRollbackSpec) {
	*out = *in
	if in.Triggers != nil {
		in, out := &in.Triggers, &out.Triggers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoRollbackSpec.
func (in *AutoRollbackSpec) DeepCopy() *AutoRollbackSpec {
	if in == nil {
		return nil
	}
	out := new(AutoRollbackSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BidirectionalGuardrailsSpec) DeepCopyInto(out *BidirectionalGuardrailsSpec) {
	*out = *in
	if in.ExcludePatterns != nil {
		in, out := &in.ExcludePatterns, &out.ExcludePatterns
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BidirectionalGuardrailsSpec.
func (in *BidirectionalGuardrailsSpec) DeepCopy() *BidirectionalGuardrailsSpec {
	if in == nil {
		return nil
	}
	out := new(BidirectionalGuardrailsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BidirectionalSpec) DeepCopyInto(out *BidirectionalSpec) {
	*out = *in
	if in.WatchPaths != nil {
		in, out := &in.WatchPaths, &out.WatchPaths
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PRLabels != nil {
		in, out := &in.PRLabels, &out.PRLabels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Guardrails != nil {
		in, out := &in.Guardrails, &out.Guardrails
		*out = new(BidirectionalGuardrailsSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BidirectionalSpec.
func (in *BidirectionalSpec) DeepCopy() *BidirectionalSpec {
	if in == nil {
		return nil
	}
	out := new(BidirectionalSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentModeSpec) DeepCopyInto(out *DeploymentModeSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentModeSpec.
func (in *DeploymentModeSpec) DeepCopy() *DeploymentModeSpec {
	if in == nil {
		return nil
	}
	out := new(DeploymentModeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentStage) DeepCopyInto(out *DeploymentStage) {
	*out = *in
	if in.GatewaySelector != nil {
		in, out := &in.GatewaySelector, &out.GatewaySelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentStage.
func (in *DeploymentStage) DeepCopy() *DeploymentStage {
	if in == nil {
		return nil
	}
	out := new(DeploymentStage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentStrategySpec) DeepCopyInto(out *DeploymentStrategySpec) {
	*out = *in
	if in.Stages != nil {
		in, out := &in.Stages, &out.Stages
		*out = make([]DeploymentStage, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SyncOrder != nil {
		in, out := &in.SyncOrder, &out.SyncOrder
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AutoRollback != nil {
		in, out := &in.AutoRollback, &out.AutoRollback
		*out = new(AutoRollbackSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentStrategySpec.
func (in *DeploymentStrategySpec) DeepCopy() *DeploymentStrategySpec {
	if in == nil {
		return nil
	}
	out := new(DeploymentStrategySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiscoveredGateway) DeepCopyInto(out *DiscoveredGateway) {
	*out = *in
	if in.LastSyncTime != nil {
		in, out := &in.LastSyncTime, &out.LastSyncTime
		*out = (*in).DeepCopy()
	}
	if in.ProjectsSynced != nil {
		in, out := &in.ProjectsSynced, &out.ProjectsSynced
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LastSnapshot != nil {
		in, out := &in.LastSnapshot, &out.LastSnapshot
		*out = new(GatewaySnapshot)
		(*in).DeepCopyInto(*out)
	}
	if in.SyncHistory != nil {
		in, out := &in.SyncHistory, &out.SyncHistory
		*out = make([]SyncHistoryEntry, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiscoveredGateway.
func (in *DiscoveredGateway) DeepCopy() *DiscoveredGateway {
	if in == nil {
		return nil
	}
	out := new(DiscoveredGateway)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DryRunDiffSummary) DeepCopyInto(out *DryRunDiffSummary) {
	*out = *in
	if in.LastEvaluated != nil {
		in, out := &in.LastEvaluated, &out.LastEvaluated
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DryRunDiffSummary.
func (in *DryRunDiffSummary) DeepCopy() *DryRunDiffSummary {
	if in == nil {
		return nil
	}
	out := new(DryRunDiffSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalResourcesSpec) DeepCopyInto(out *ExternalResourcesSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalResourcesSpec.
func (in *ExternalResourcesSpec) DeepCopy() *ExternalResourcesSpec {
	if in == nil {
		return nil
	}
	out := new(ExternalResourcesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FieldReplacement) DeepCopyInto(out *FieldReplacement) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FieldReplacement.
func (in *FieldReplacement) DeepCopy() *FieldReplacement {
	if in == nil {
		return nil
	}
	out := new(FieldReplacement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewaySnapshot) DeepCopyInto(out *GatewaySnapshot) {
	*out = *in
	if in.Timestamp != nil {
		in, out := &in.Timestamp, &out.Timestamp
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewaySnapshot.
func (in *GatewaySnapshot) DeepCopy() *GatewaySnapshot {
	if in == nil {
		return nil
	}
	out := new(GatewaySnapshot)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewaySpec) DeepCopyInto(out *GatewaySpec) {
	*out = *in
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(bool)
		**out = **in
	}
	out.APIKeySecretRef = in.APIKeySecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewaySpec.
func (in *GatewaySpec) DeepCopy() *GatewaySpec {
	if in == nil {
		return nil
	}
	out := new(GatewaySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitAuthSpec) DeepCopyInto(out *GitAuthSpec) {
	*out = *in
	if in.SSHKey != nil {
		in, out := &in.SSHKey, &out.SSHKey
		*out = new(SSHKeyAuth)
		**out = **in
	}
	if in.GitHubApp != nil {
		in, out := &in.GitHubApp, &out.GitHubApp
		*out = new(GitHubAppAuth)
		**out = **in
	}
	if in.Token != nil {
		in, out := &in.Token, &out.Token
		*out = new(TokenAuth)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitAuthSpec.
func (in *GitAuthSpec) DeepCopy() *GitAuthSpec {
	if in == nil {
		return nil
	}
	out := new(GitAuthSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubAppAuth) DeepCopyInto(out *GitHubAppAuth) {
	*out = *in
	out.PrivateKeySecretRef = in.PrivateKeySecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubAppAuth.
func (in *GitHubAppAuth) DeepCopy() *GitHubAppAuth {
	if in == nil {
		return nil
	}
	out := new(GitHubAppAuth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitSpec) DeepCopyInto(out *GitSpec) {
	*out = *in
	if in.Auth != nil {
		in, out := &in.Auth, &out.Auth
		*out = new(GitAuthSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitSpec.
func (in *GitSpec) DeepCopy() *GitSpec {
	if in == nil {
		return nil
	}
	out := new(GitSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IgnitionSpec) DeepCopyInto(out *IgnitionSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IgnitionSpec.
func (in *IgnitionSpec) DeepCopy() *IgnitionSpec {
	if in == nil {
		return nil
	}
	out := new(IgnitionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IgnitionSync) DeepCopyInto(out *IgnitionSync) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IgnitionSync.
func (in *IgnitionSync) DeepCopy() *IgnitionSync {
	if in == nil {
		return nil
	}
	out := new(IgnitionSync)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IgnitionSync) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IgnitionSyncList) DeepCopyInto(out *IgnitionSyncList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]IgnitionSync, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IgnitionSyncList.
func (in *IgnitionSyncList) DeepCopy() *IgnitionSyncList {
	if in == nil {
		return nil
	}
	out := new(IgnitionSyncList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IgnitionSyncList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IgnitionSyncSpec) DeepCopyInto(out *IgnitionSyncSpec) {
	*out = *in
	in.Git.DeepCopyInto(&out.Git)
	in.Webhook.DeepCopyInto(&out.Webhook)
	in.Polling.DeepCopyInto(&out.Polling)
	in.Gateway.DeepCopyInto(&out.Gateway)
	in.Shared.DeepCopyInto(&out.Shared)
	if in.AdditionalFiles != nil {
		in, out := &in.AdditionalFiles, &out.AdditionalFiles
		*out = make([]AdditionalFile, len(*in))
		copy(*out, *in)
	}
	if in.ExcludePatterns != nil {
		in, out := &in.ExcludePatterns, &out.ExcludePatterns
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.Normalize.DeepCopyInto(&out.Normalize)
	if in.Bidirectional != nil {
		in, out := &in.Bidirectional, &out.Bidirectional
		*out = new(BidirectionalSpec)
		(*in).DeepCopyInto(*out)
	}
	in.Validation.DeepCopyInto(&out.Validation)
	if in.Snapshots != nil {
		in, out := &in.Snapshots, &out.Snapshots
		*out = new(SnapshotSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Deployment != nil {
		in, out := &in.Deployment, &out.Deployment
		*out = new(DeploymentStrategySpec)
		(*in).DeepCopyInto(*out)
	}
	out.Ignition = in.Ignition
	in.Agent.DeepCopyInto(&out.Agent)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IgnitionSyncSpec.
func (in *IgnitionSyncSpec) DeepCopy() *IgnitionSyncSpec {
	if in == nil {
		return nil
	}
	out := new(IgnitionSyncSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IgnitionSyncStatus) DeepCopyInto(out *IgnitionSyncStatus) {
	*out = *in
	if in.LastSyncTime != nil {
		in, out := &in.LastSyncTime, &out.LastSyncTime
		*out = (*in).DeepCopy()
	}
	if in.DiscoveredGateways != nil {
		in, out := &in.DiscoveredGateways, &out.DiscoveredGateways
		*out = make([]DiscoveredGateway, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IgnitionSyncStatus.
func (in *IgnitionSyncStatus) DeepCopy() *IgnitionSyncStatus {
	if in == nil {
		return nil
	}
	out := new(IgnitionSyncStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NormalizeSpec) DeepCopyInto(out *NormalizeSpec) {
	*out = *in
	if in.Fields != nil {
		in, out := &in.Fields, &out.Fields
		*out = make([]FieldReplacement, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NormalizeSpec.
func (in *NormalizeSpec) DeepCopy() *NormalizeSpec {
	if in == nil {
		return nil
	}
	out := new(NormalizeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PollingSpec) DeepCopyInto(out *PollingSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PollingSpec.
func (in *PollingSpec) DeepCopy() *PollingSpec {
	if in == nil {
		return nil
	}
	out := new(PollingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProfileDependency) DeepCopyInto(out *ProfileDependency) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProfileDependency.
func (in *ProfileDependency) DeepCopy() *ProfileDependency {
	if in == nil {
		return nil
	}
	out := new(ProfileDependency)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3StorageSpec) DeepCopyInto(out *S3StorageSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3StorageSpec.
func (in *S3StorageSpec) DeepCopy() *S3StorageSpec {
	if in == nil {
		return nil
	}
	out := new(S3StorageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SSHKeyAuth) DeepCopyInto(out *SSHKeyAuth) {
	*out = *in
	out.SecretRef = in.SecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SSHKeyAuth.
func (in *SSHKeyAuth) DeepCopy() *SSHKeyAuth {
	if in == nil {
		return nil
	}
	out := new(SSHKeyAuth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScriptsSpec) DeepCopyInto(out *ScriptsSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScriptsSpec.
func (in *ScriptsSpec) DeepCopy() *ScriptsSpec {
	if in == nil {
		return nil
	}
	out := new(ScriptsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKeyRef) DeepCopyInto(out *SecretKeyRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKeyRef.
func (in *SecretKeyRef) DeepCopy() *SecretKeyRef {
	if in == nil {
		return nil
	}
	out := new(SecretKeyRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SharedSpec) DeepCopyInto(out *SharedSpec) {
	*out = *in
	if in.ExternalResources != nil {
		in, out := &in.ExternalResources, &out.ExternalResources
		*out = new(ExternalResourcesSpec)
		**out = **in
	}
	if in.Scripts != nil {
		in, out := &in.Scripts, &out.Scripts
		*out = new(ScriptsSpec)
		**out = **in
	}
	if in.UDTs != nil {
		in, out := &in.UDTs, &out.UDTs
		*out = new(UDTsSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SharedSpec.
func (in *SharedSpec) DeepCopy() *SharedSpec {
	if in == nil {
		return nil
	}
	out := new(SharedSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SnapshotSpec) DeepCopyInto(out *SnapshotSpec) {
	*out = *in
	if in.Storage != nil {
		in, out := &in.Storage, &out.Storage
		*out = new(SnapshotStorageSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SnapshotSpec.
func (in *SnapshotSpec) DeepCopy() *SnapshotSpec {
	if in == nil {
		return nil
	}
	out := new(SnapshotSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SnapshotStorageSpec) DeepCopyInto(out *SnapshotStorageSpec) {
	*out = *in
	if in.S3 != nil {
		in, out := &in.S3, &out.S3
		*out = new(S3StorageSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SnapshotStorageSpec.
func (in *SnapshotStorageSpec) DeepCopy() *SnapshotStorageSpec {
	if in == nil {
		return nil
	}
	out := new(SnapshotStorageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SyncHistoryEntry) DeepCopyInto(out *SyncHistoryEntry) {
	*out = *in
	if in.Timestamp != nil {
		in, out := &in.Timestamp, &out.Timestamp
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SyncHistoryEntry.
func (in *SyncHistoryEntry) DeepCopy() *SyncHistoryEntry {
	if in == nil {
		return nil
	}
	out := new(SyncHistoryEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SyncMapping) DeepCopyInto(out *SyncMapping) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SyncMapping.
func (in *SyncMapping) DeepCopy() *SyncMapping {
	if in == nil {
		return nil
	}
	out := new(SyncMapping)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SyncProfile) DeepCopyInto(out *SyncProfile) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SyncProfile.
func (in *SyncProfile) DeepCopy() *SyncProfile {
	if in == nil {
		return nil
	}
	out := new(SyncProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SyncProfile) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SyncProfileList) DeepCopyInto(out *SyncProfileList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SyncProfile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SyncProfileList.
func (in *SyncProfileList) DeepCopy() *SyncProfileList {
	if in == nil {
		return nil
	}
	out := new(SyncProfileList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SyncProfileList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SyncProfileSpec) DeepCopyInto(out *SyncProfileSpec) {
	*out = *in
	if in.Mappings != nil {
		in, out := &in.Mappings, &out.Mappings
		*out = make([]SyncMapping, len(*in))
		copy(*out, *in)
	}
	if in.DeploymentMode != nil {
		in, out := &in.DeploymentMode, &out.DeploymentMode
		*out = new(DeploymentModeSpec)
		**out = **in
	}
	if in.ExcludePatterns != nil {
		in, out := &in.ExcludePatterns, &out.ExcludePatterns
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DependsOn != nil {
		in, out := &in.DependsOn, &out.DependsOn
		*out = make([]ProfileDependency, len(*in))
		copy(*out, *in)
	}
	if in.Vars != nil {
		in, out := &in.Vars, &out.Vars
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SyncProfileSpec.
func (in *SyncProfileSpec) DeepCopy() *SyncProfileSpec {
	if in == nil {
		return nil
	}
	out := new(SyncProfileSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SyncProfileStatus) DeepCopyInto(out *SyncProfileStatus) {
	*out = *in
	if in.DryRunDiff != nil {
		in, out := &in.DryRunDiff, &out.DryRunDiff
		*out = new(DryRunDiffSummary)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SyncProfileStatus.
func (in *SyncProfileStatus) DeepCopy() *SyncProfileStatus {
	if in == nil {
		return nil
	}
	out := new(SyncProfileStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TokenAuth) DeepCopyInto(out *TokenAuth) {
	*out = *in
	out.SecretRef = in.SecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TokenAuth.
func (in *TokenAuth) DeepCopy() *TokenAuth {
	if in == nil {
		return nil
	}
	out := new(TokenAuth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UDTsSpec) DeepCopyInto(out *UDTsSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UDTsSpec.
func (in *UDTsSpec) DeepCopy() *UDTsSpec {
	if in == nil {
		return nil
	}
	out := new(UDTsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValidationSpec) DeepCopyInto(out *ValidationSpec) {
	*out = *in
	if in.Webhook != nil {
		in, out := &in.Webhook, &out.Webhook
		*out = new(ValidationWebhookSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValidationSpec.
func (in *ValidationSpec) DeepCopy() *ValidationSpec {
	if in == nil {
		return nil
	}
	out := new(ValidationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValidationWebhookSpec) DeepCopyInto(out *ValidationWebhookSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValidationWebhookSpec.
func (in *ValidationWebhookSpec) DeepCopy() *ValidationWebhookSpec {
	if in == nil {
		return nil
	}
	out := new(ValidationWebhookSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebhookSpec) DeepCopyInto(out *WebhookSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(SecretKeyRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebhookSpec.
func (in *WebhookSpec) DeepCopy() *WebhookSpec {
	if in == nil {
		return nil
	}
	out := new(WebhookSpec)
	in.DeepCopyInto(out)
	return out
}
